apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "browserless.fullname" . }}
  labels:
    {{- include "browserless.labels" . | nindent 4 }}
data:
  ALLOW_FILE_PROTOCOL: '{{ .Values.config.ALLOW_FILE_PROTOCOL }}'
  CONCURRENT: '{{ .Values.config.CONCURRENT }}'
  CORS: '{{ .Values.config.CORS }}'
  CORS_ALLOW_METHODS: '{{ .Values.config.CORS_ALLOW_METHODS }}'
  CORS_ALLOW_ORIGIN: '{{ .Values.config.CORS_ALLOW_ORIGIN }}'
  HEALTH: '{{ .Values.config.HEALTH }}'
  QUEUED: '{{ .Values.config.QUEUED }}'
  TIMEOUT: '{{ .Values.config.TIMEOUT }}'
  TOKEN: '{{ .Values.config.TOKEN }}'
  {{- with .Values.additionalEnvVars }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
